baseurl = "/"
languageCode = "en-US"
title = "SDS 348 Portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "Screenshot (290).png"
  author = "Cynthia Kulak"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "cyn-k"
  Email         = "cynthia.kulak@gmail.com"
  Twitter       = "ck__bunny"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 300
  url = "/about/"
