---
title: "Project 2"
author: "Cynthia Kulak cek2338"
date: "5/1/2020"
output:
  pdf_document: default
  html_document: default
---



<div id="libraries" class="section level2">
<h2>Libraries</h2>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages ---------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.2.1     v purrr   0.3.3
## v tibble  2.1.3     v stringr 1.4.0
## v tidyr   1.0.2     v forcats 0.4.0
## v readr   1.3.1</code></pre>
<pre><code>## -- Conflicts ------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(ggplot2)
library(sandwich)</code></pre>
<pre><code>## Warning: package &#39;sandwich&#39; was built under R version 3.6.3</code></pre>
<pre class="r"><code>library(lmtest)</code></pre>
<pre><code>## Warning: package &#39;lmtest&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## Warning: package &#39;zoo&#39; was built under R version 3.6.3</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>library(nnet)
library(plotROC)</code></pre>
<pre><code>## Warning: package &#39;plotROC&#39; was built under R version 3.6.3</code></pre>
<pre class="r"><code>library(pROC)</code></pre>
<pre><code>## Warning: package &#39;pROC&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Type &#39;citation(&quot;pROC&quot;)&#39; for a citation.</code></pre>
<pre><code>## 
## Attaching package: &#39;pROC&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:plotROC&#39;:
## 
##     ggroc</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     cov, smooth, var</code></pre>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Warning: package &#39;glmnet&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 3.0-2</code></pre>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<pre class="r"><code>possum&lt;-read.csv(&quot;possum.csv&quot;)
possum&lt;-possum%&gt;%select(-1, -2, -4, -7, -8, -11, -12, -13)</code></pre>
<p>I chose to use the possum dataset for this project, which has 15 variables and 104 observations of morphometric measurements of possums in Australia. I chose to tidy the data to include only the variables I wanted focus on which are: site, sex, age, totlnght, taill, chest, and belly. Site is one of the seven sites the possum was captured, age is in years, totlngth is the total length of the possum, taill is the length of the tail, chest is the measurement of the girth of the chest, and belly is the measurement of the girth of the belly. All numerric measurements (other than site and age) are in cm.</p>
</div>
<div id="manova" class="section level2">
<h2>Manova</h2>
<pre class="r"><code>#MANOVA
#sex
possum_sex_manova &lt;- manova(cbind(age, totlngth, taill, chest, belly) ~ sex, data = possum)
summary(possum_sex_manova)</code></pre>
<pre><code>##            Df   Pillai approx F num Df den Df Pr(&gt;F)
## sex         1 0.024782  0.48791      5     96 0.7845
## Residuals 100</code></pre>
<pre class="r"><code>#site
possum_site&lt;-possum%&gt;%
  mutate(site = recode(site, &quot;1&quot;=&quot;one&quot;, &quot;2&quot;=&quot;two&quot;, &quot;3&quot;=&quot;three&quot;, &quot;4&quot;=&quot;four&quot;, &quot;5&quot;=&quot;five&quot;, &quot;6&quot;=&quot;six&quot;, &quot;7&quot;=&quot;seven&quot;))
possum_site_manova &lt;- manova(cbind(age, totlngth, taill, chest, belly) ~ site, data = possum_site)
summary(possum_site_manova)</code></pre>
<pre><code>##           Df Pillai approx F num Df den Df    Pr(&gt;F)    
## site       6 1.2153   5.0842     30    475 1.864e-15 ***
## Residuals 95                                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#univariate ANOVAs
summary.aov(possum_site_manova)</code></pre>
<pre><code>##  Response age :
##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## site         6  17.69  2.9484  0.7992 0.5729
## Residuals   95 350.48  3.6892               
## 
##  Response totlngth :
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## site         6 812.52 135.421  13.306 6.863e-11 ***
## Residuals   95 966.84  10.177                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response taill :
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## site         6 141.04 23.5072  9.0045 8.735e-08 ***
## Residuals   95 248.01  2.6106                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response chest :
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## site         6 132.21 22.0350  7.5811 1.165e-06 ***
## Residuals   95 276.13  2.9066                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response belly :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## site         6 129.57  21.595  3.3142 0.00525 **
## Residuals   95 619.02   6.516                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## 2 observations deleted due to missingness</code></pre>
<pre class="r"><code>#age = no mean difference between site (.57)
#total length = mean difference between site (6.86e^-11)
#tail length = mean difference between site (8.74e^-8)
#chest girth = mean difference between site (1.17e^-6)
#belly girth = mean difference between site (.005)

#post-hoc t tests
pairwise.t.test(possum_site$age, possum$site, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  possum_site$age and possum$site 
## 
##   1    2    3    4    5    6   
## 2 0.34 -    -    -    -    -   
## 3 0.90 0.43 -    -    -    -   
## 4 0.27 0.78 0.33 -    -    -   
## 5 0.84 0.34 0.98 0.26 -    -   
## 6 0.17 0.76 0.28 0.98 0.19 -   
## 7 0.19 0.89 0.33 0.85 0.22 0.85
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#none of the groups differ which we knew already

#with adjustment of 0.00122:
  #still none

pairwise.t.test(possum_site$totlngth, possum$site, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  possum_site$totlngth and possum$site 
## 
##   1       2       3       4       5       6      
## 2 2.6e-11 -       -       -       -       -      
## 3 0.22386 6.5e-05 -       -       -       -      
## 4 0.06198 4.5e-10 0.01725 -       -       -      
## 5 0.00954 9.3e-05 0.44878 0.00065 -       -      
## 6 3.8e-06 0.03077 0.02134 1.7e-06 0.06207 -      
## 7 4.8e-05 0.00116 0.10079 1.5e-05 0.29722 0.32654
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#1 and 5,6,7
#2 and all
#3 and 4
#4 and 5,6,7

#with adjustment of 0.00122:
  #1 and 2,6,7
  #2 and 3,4,5,7
  #4 and 5,6,7

pairwise.t.test(possum_site$taill, possum$site, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  possum_site$taill and possum$site 
## 
##   1       2       3      4      5      6     
## 2 0.0035  -       -      -      -      -     
## 3 0.2128  0.0018  -      -      -      -     
## 4 2.5e-06 2.9e-09 0.0043 -      -      -     
## 5 0.0168  1.7e-05 0.5594 0.0072 -      -     
## 6 0.0168  1.7e-05 0.5594 0.0072 1.0000 -     
## 7 0.0061  3.1e-06 0.5023 0.0056 0.9446 0.9446
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#1 and 4,5,6,7
#2 and all
#3 and 4
#4 and 5,6,7

#with adjustment of 0.00122:
  #1 and 4
  #2 and 4,5,6

pairwise.t.test(possum_site$chest, possum$site, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  possum_site$chest and possum$site 
## 
##   1       2       3       4       5       6      
## 2 0.00836 -       -       -       -       -      
## 3 0.67188 0.13600 -       -       -       -      
## 4 0.01657 0.00011 0.02812 -       -       -      
## 5 0.03390 0.65284 0.26302 0.00040 -       -      
## 6 1.0e-05 0.10515 0.00501 4.5e-07 0.03952 -      
## 7 0.00093 0.74396 0.06738 1.7e-05 0.41775 0.15447
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#1 and 2,4,5,6,7
#2 and 4
#3 and 4,6
#4 and 5,6,7
#5 and 6

#with adjustment of 0.00122:
  #1 and 6,7
  #2 and 4
  #4 and 5,6,7

pairwise.t.test(possum_site$belly, possum$site, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  possum_site$belly and possum$site 
## 
##   1      2      3      4      5      6     
## 2 0.0126 -      -      -      -      -     
## 3 0.1449 0.0027 -      -      -      -     
## 4 0.2313 0.0054 0.8370 -      -      -     
## 5 0.1489 0.3659 0.0224 0.0396 -      -     
## 6 0.0393 0.7059 0.0068 0.0131 0.5974 -     
## 7 0.0772 0.3976 0.0124 0.0236 0.8975 0.6596
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#1 and 2,6
#2 and 3,4
#3 and 4,5,6
#4 and 5,6,7

#with adjustment of 0.00122:
  #none

#1 manova
#5 measurements = 5 anovas
#7 sites * 5 measurements = 35 t-tests
#41 tests total (not including the first manova using sex)

#type-I error
1 - (0.95^41)</code></pre>
<pre><code>## [1] 0.8779135</code></pre>
<pre class="r"><code>#0.878

#bonferroni correction
0.05/41</code></pre>
<pre><code>## [1] 0.001219512</code></pre>
<pre class="r"><code>#0.00122

#assumptions
  #homogeneity of (co)variances
covmats&lt;-possum_site%&gt;%group_by(site)%&gt;%do(covs=cov(.[3:7]))
for(i in 1:7){print(as.character(covmats$site[i])); print(covmats$covs[i])}</code></pre>
<pre><code>## [1] &quot;five&quot;
## [[1]]
##               age totlngth     taill     chest    belly
## age      4.064103 3.317308 1.5320513 1.5320513 1.778846
## totlngth 3.317308 9.035256 3.4503205 2.2419872 4.086538
## taill    1.532051 3.450321 1.6410256 0.6410256 1.368590
## chest    1.532051 2.241987 0.6410256 2.0576923 3.014423
## belly    1.778846 4.086538 1.3685897 3.0144231 8.560897
## 
## [1] &quot;four&quot;
## [[1]]
##                 age    totlngth      taill     chest     belly
## age       3.2380952 -0.33095238 2.76190476 0.5357143  2.309524
## totlngth -0.3309524  6.16285714 0.09761905 3.5178571  4.088095
## taill     2.7619048  0.09761905 3.23809524 1.2976190  3.273810
## chest     0.5357143  3.51785714 1.29761905 4.4761905  5.529762
## belly     2.3095238  4.08809524 3.27380952 5.5297619 10.035714
## 
## [1] &quot;one&quot;
## [[1]]
##               age totlngth    taill    chest    belly
## age      4.590909 1.647727 1.053977 1.022727 1.558239
## totlngth 1.647727 8.937973 3.565578 2.831203 2.815341
## taill    1.053977 3.565578 2.625473 1.133286 1.643466
## chest    1.022727 2.831203 1.133286 3.484848 2.393466
## belly    1.558239 2.815341 1.643466 2.393466 5.595170
## 
## [1] &quot;seven&quot;
## [[1]]
##                  age    totlngth      taill      chest     belly
## age       2.84967320 -0.03267974 -1.5326797  1.7581699 0.2745098
## totlngth -0.03267974  9.70996732  3.0776144  1.4714052 3.0318627
## taill    -1.53267974  3.07761438  2.7099673 -0.7344771 1.7524510
## chest     1.75816993  1.47140523 -0.7344771  3.1707516 2.0269608
## belly     0.27450980  3.03186275  1.7524510  2.0269608 4.8308824
## 
## [1] &quot;six&quot;
## [[1]]
##                age  totlngth     taill    chest    belly
## age      2.8974359  2.653846 0.4903846 1.589744 3.125000
## totlngth 2.6538462 13.352564 5.2227564 3.552885 4.520833
## taill    0.4903846  5.222756 2.7243590 1.294872 1.437500
## chest    1.5897436  3.552885 1.2948718 2.483974 2.687500
## belly    3.1250000  4.520833 1.4375000 2.687500 6.250000
## 
## [1] &quot;three&quot;
## [[1]]
##                  age    totlngth      taill      chest      belly
## age       1.90476190 -0.02380952  0.0952381  1.6428571  0.8809524
## totlngth -0.02380952 11.20238095  5.3154762 -1.7559524 -5.3630952
## taill     0.09523810  5.31547619  3.4880952 -0.2261905 -2.0476190
## chest     1.64285714 -1.75595238 -0.2261905  2.3690476  1.3452381
## belly     0.88095238 -5.36309524 -2.0476190  1.3452381  4.3095238
## 
## [1] &quot;two&quot;
## [[1]]
##          age  totlngth      taill      chest      belly
## age       NA        NA         NA         NA         NA
## totlngth  NA 15.192308  2.7019231  2.2948718  8.1121795
## taill     NA  2.701923  2.1474359 -0.3445513 -0.4967949
## chest     NA  2.294872 -0.3445513  2.6826923  1.3317308
## belly     NA  8.112179 -0.4967949  1.3317308 10.5064103</code></pre>
<p>First I tried to ru the MANOVA with the binary variable, sex, but the p-value was not significant (0.78), so there isn’t a mean difference between the sexes for any of the measurements. To continue with the rest of the question, I decided to try it with the categorical variable, site. First I had to tidy the data to switch site from being numeric to categorical, then I ran the MANOVA. This time, the p-value was significant (1.86e^-15), so at least some of the numerics have a mean difference between the sites. Then I ran 5 univariate ANOVAs and 35 post-hoc t tests to find which groups differ. I ran 41 tests in total, and have an 87.8% chance of having a type-1 error. I used a bonferroni correction to adjust the significance levels, which led me to the conclusion that none of the sites differ by age or by belly girth, and sites 2 and 4 differ across all other variables. When checking the assumption of homogeneity of (co)variances, all the numbers across all the sites varied, which leads me to believe that the assumption isn’t met.</p>
</div>
<div id="randomization" class="section level2">
<h2>Randomization</h2>
<pre class="r"><code>#randomization
set.seed(348)
possum_site%&gt;%group_by(sex)%&gt;%summarize(s=sd(totlngth))%&gt;%summarize(diff(s))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `diff(s)`
##       &lt;dbl&gt;
## 1     0.158</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
  new&lt;-data.frame(totlngth=sample(possum_site$totlngth),sex=possum_site$sex)
  rand_dist[i]&lt;-mean(new[new$sex==&quot;m&quot;,]$totlngth)-
    mean(new[new$sex==&quot;f&quot;,]$totlngth)
  }

mean(rand_dist&lt; -0.1576551 | rand_dist &gt; 0.1576551)</code></pre>
<pre><code>## [1] 0.8488</code></pre>
<pre class="r"><code>#0.8484


#plot
{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = 0.1576551,col=&quot;red&quot;)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" />
Null hypothesis: the mean of the total length of possums is the same for males and females. Alternative hypothesis: the mean of the total length of possums is different for males and females. Because the p-value is 0.8484, we fail to reject the null hypothesis and conclude that the total length of possums is the same for males and females. This supports the conclusion made from part one using MANOVA to check for any mean differences of the measurements between the sexes.</p>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear Regression</h2>
<pre class="r"><code>possum_na&lt;-possum_site%&gt;%na.omit

#centering 
possum_na$totlngth_c &lt;- possum_na$totlngth - mean(possum_na$totlngth, na.rm = T)
possum_na$taill_c &lt;- possum_na$taill - mean(possum_na$taill, na.rm = T)

#linear regression
fit&lt;-lm(totlngth_c ~ age+taill_c+age*taill_c, data=possum_na)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = totlngth_c ~ age + taill_c + age * taill_c, data = possum_na)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.0547 -2.2983 -0.1382  2.1202  6.8185 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.61133    0.75938  -2.122   0.0364 *  
## age          0.43589    0.17763   2.454   0.0159 *  
## taill_c      1.67094    0.39022   4.282 4.32e-05 ***
## age:taill_c -0.13577    0.09207  -1.475   0.1435    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.384 on 98 degrees of freedom
## Multiple R-squared:  0.3693, Adjusted R-squared:   0.35 
## F-statistic: 19.13 on 3 and 98 DF,  p-value: 7.617e-10</code></pre>
<pre class="r"><code>#plot
qplot(x = taill_c, y = totlngth_c, color = age, data = possum_na) +
  stat_smooth(method = &quot;lm&quot;, se = FALSE, fullrange = TRUE)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>#assumptions 
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>#pretty scattered so meets homoskedsaticity assumption
ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<pre class="r"><code>#normal distribution
ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids), color=&#39;red&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-4.png" width="672" /></p>
<pre class="r"><code>#relatively linear

#regression with robust standard errors
coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.611332   0.849290 -1.8973 0.060736 .  
## age          0.435886   0.184568  2.3617 0.020171 *  
## taill_c      1.670938   0.414032  4.0358 0.000108 ***
## age:taill_c -0.135770   0.091149 -1.4895 0.139556    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#What proportion of the variation in the outcome does your model explain?
(sum((possum_na$totlngth-mean(possum_na$totlngth))^2)-
    sum(fit$residuals^2))/
  sum((possum_na$totlngth-mean(possum_na$totlngth))^2)</code></pre>
<pre><code>## [1] 0.3693389</code></pre>
<p>After running the linear regression, according to the intercept, when age and tail length are 0, the total length of a possum is -1.6. When keeping tail length fixed, for every one unit increase in age, total possum length increases by 0.44. When keeping age fixed, for every one unit increase in tail length, there is a 1.67 unit increase in total possum length. When accounting for the interaction between tail length and age, the total possum length decreases by 0.14.
When checking for assumptions through graphs, the points on the scatterplot are pretty scattered which suggests it meets the homoskedsaticity assumption, the histogram has a normal distribution, and the points on the last graph follow the line pretty well, which suggests it meets the linearity assumption.
After recomputing with robust standard errors, the estimates didn’t change, but the standard errors increased slightly for all except the interaction between tail length and age.
About 37% of the variation in the outcome is explained by the model.</p>
</div>
<div id="bootstrap" class="section level2">
<h2>Bootstrap</h2>
<pre class="r"><code>set.seed(123)
samp_distn&lt;-replicate(5000, {
boot_dat &lt;- possum_na[sample(nrow(possum_na), replace=TRUE),] #bootstrap your data
fit &lt;- lm(totlngth_c~age+taill_c+age*taill_c, data=boot_dat) #fit model
coef(fit) #save coefs
})

## Estimated SEs
samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)       age   taill_c age:taill_c
## 1   0.8196455 0.1768732 0.4154114   0.0927319</code></pre>
<pre class="r"><code>## Empirical 95% CI
samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% gather %&gt;% group_by(key) %&gt;%
summarize(lower=quantile(value,.025), upper=quantile(value,.975))</code></pre>
<pre><code>## # A tibble: 4 x 3
##   key           lower  upper
##   &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;
## 1 (Intercept) -3.21   0.0146
## 2 age          0.0899 0.773 
## 3 age:taill_c -0.303  0.0667
## 4 taill_c      0.798  2.44</code></pre>
<p>The bootstrapped standard errors are very slightly higher than the original standard errors, except for age is very slightly lower. Compared to the robust standard errors, the bootstrapped standard errors are slightly lower for all except the interaction between age and tail length.</p>
</div>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<pre class="r"><code>possum_binary&lt;-possum_na%&gt;%mutate(y=ifelse(sex==&quot;m&quot;,1,0))
fit1&lt;-glm(y~site+totlngth_c,data=possum_binary,family=binomial(link=&quot;logit&quot;))
exp(coeftest(fit1))</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  1.14639    1.74866  1.2769    2.241
## sitefour     3.00879    2.92167  2.7938    1.356
## siteone      0.75022    1.98408  0.6574    1.964
## siteseven    2.79900    2.22553  3.6204    1.219
## sitesix      1.67071    2.30697  1.8478    1.715
## sitethree    1.22988    2.59201  1.2427    2.289
## sitetwo      0.75839    2.43176  0.7325    2.129
## totlngth_c   0.93869    1.07025  0.3938    1.421</code></pre>
<pre class="r"><code>#confusion matrix
prob&lt;-predict(fit1, type=&quot;response&quot;)
truth&lt;-fit1$y
class_diag &lt;- function(probs,truth){
#CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
#CALCULATE EXACT AUC
ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
}
#acc = 0.63
#sens = 0.76
#spec = 0.44
#ppv = 0.65
#auc = 0.41

#plot density of log-odds by binary outcome variable
possum_binary$y&lt;-as.factor(possum_binary$y)
possum_binary$logit&lt;-predict(fit1, type=&quot;link&quot;)
possum_binary%&gt;%ggplot()+geom_density(aes(logit, color=y, fill=y), alpha=.5)+
  xlab(&quot;logg-odds(logit)&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>#ROC curve and calculate AUC
fit_plot&lt;-ggplot(fit1)+geom_roc(aes(d=y,m=totlngth_c,color=y),n.cuts=0)
fit_plot</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(fit_plot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.4136776</code></pre>
<pre class="r"><code>  #0.41

#10-fold CV and report average out-of-sample Accuracy, Sensitivity, and Recall
set.seed(1234)
k=10
data&lt;-possum_binary[sample(nrow(possum_binary)),] #put dataset in random order
folds&lt;-cut(seq(1:nrow(possum_binary)),breaks=k,labels=F) #create folds
diags&lt;-NULL
for(i in 1:k){ # FOR EACH OF 10 FOLDS
train&lt;-data[folds!=i,] # CREATE TRAINING SET
test&lt;-data[folds==i,] # CREATE TESTING SET
truth&lt;-test$y
fit&lt;-glm(y~site+totlngth_c, data=train, family=&quot;binomial&quot;)
probs&lt;- predict(fit,newdata = test,type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs,truth)) #CV DIAGNOSTICS FOR EACH FOLD
}
summarize_all(diags,mean) #AVERAGE THE DIAGNOSTICS ACROSS THE 10 FOLDS</code></pre>
<pre><code>##         acc      sens      spec       ppv     auc
## 1 0.5309091 0.6682143 0.3566667 0.5901587 0.58025</code></pre>
<pre class="r"><code>  #acc = 0.49
  #sens = 0.61
  #ppv = 0.59</code></pre>
<p>From the logistic regression, at site 4 when keeping total length fixed, there is a 3x higher chance that a possum is male. At site 1 when keeping total length fixed, there is a 0.75 chance that a possum is male. Whe keeping site location fixed, for every one unit increase it total possum length, the chance of a possum being male increases by 0.94.
From the confusion matrix, the accuracy is 0.63, the sensitivity is 0.76, the specificity is 0.44, and the recall is 0.65. The calculated AUC is 0.41, which suggests that the model is a poor predictor for real-world models. After performing a 10-fold CV, the accuracy is 0.49, the sensitivity is 0.61, and the recall is 0.59.</p>
</div>
<div id="lasso-regression" class="section level2">
<h2>LASSO Regression</h2>
<pre class="r"><code>possum&lt;-possum_binary%&gt;%select(-2, -8, -9)

set.seed(1234)
x&lt;-model.matrix(totlngth~. , data=possum)[,-1]
y&lt;-as.matrix(possum$totlngth)
cv&lt;-cv.glmnet(x,y, family=&quot;poisson&quot;)
lasso&lt;-glmnet(x,y, family=&quot;poisson&quot;, lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 13 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)  4.469465e+00
## sitefour     1.915828e-01
## siteone     -4.928220e-02
## siteseven    1.789413e-01
## sitesix      8.779477e-02
## sitethree    3.584790e-02
## sitetwo     -5.087219e-02
## age          1.311313e-04
## taill        4.684437e-04
## chest        4.320398e-05
## belly        1.001526e-04
## y1           7.626175e-06
## logit       -1.748617e-01</code></pre>
<pre class="r"><code>#10-fold CV 
set.seed(1234)
k=5 #choose number of folds
possum2&lt;-possum%&gt;%select(totlngth, site, taill, chest, belly)
data2&lt;-possum2[sample(nrow(possum2)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(possum2)),breaks=k,labels=F) #create folds
diags&lt;-NULL
for(i in 1:k){
train&lt;-data2[folds!=i,]
test&lt;-data2[folds==i,]
fit&lt;-lm(totlngth~., data=train)
yhat&lt;-predict(fit,newdata=test)
diags&lt;-mean((test$totlngth-yhat)^2)
}
mean(diags)</code></pre>
<pre><code>## [1] 6.757927</code></pre>
<p>After running the LASSO regression, the variables with a non-zero value were sites 1, 2, 5, and 6, plus tail, chest, and belly. After running the 10-fold CV, the residual standard error is 9.73, which means the fit is alright.</p>
</div>
